---
# code: language=ansible

- name: Configure Arch Linux
  hosts: local
  roles:
    - name: Apply base system configuration
      role: base
      tags: base

    - name: Install GUI and applications
      role: gui
      tags: gui

    - name: Install TLS certificates for Traefik
      role: traefik_tls
      tags: traefik_tls

    - name: Install Docker and services
      role: docker
      tags: docker
