entryPoints:
  websecure:
    address: ":443"

tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/certs/cert.pem"
        keyFile: "/certs/cert.key"

providers:
  docker:
    exposedByDefault: false

log:
  level: DEBUG
