entryPoints:
  websecure:
    address: ":443"

tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/certs/cert.pem"
        keyFile: "/certs/cert.key"

api:
  dashboard: true
  insecure: true

providers:
  docker:
    exposedByDefault: false
