---
# code: language=ansible

- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart dnsmasq
  ansible.builtin.systemd:
    name: dnsmasq
    state: restarted
