---
# code: language=ansible

- name: Install selected desktop & apps
  community.general.pacman:
    name: "{{ gui_selected | map('extract', gui_packages) | flatten | unique }}"
    state: present
    update_cache: true
  when: gui_selected | length > 0
