---
# code: language=ansible

- name: Copy config files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/home/{{ username }}/.config/"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
    directory_mode: '0755'
  loop: "{{ subfolders[desktop] }}"

- name: Copy .bash_profile
  ansible.builtin.template:
    src: .bash_profile.j2
    dest: "/home/{{ username }}/.bash_profile"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'

- name: Set executable permissions
  ansible.builtin.file:
    path: "/home/{{ username }}/{{ item }}"
    mode: '0755'
  loop: "{{ configs_exec[desktop] }}"
