---
# code: language=ansible

- name: Create .config subfolders
  ansible.builtin.file:
    path: "/home/{{ username }}/.config/{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'
  loop:
    - i3
    - alacritty

- name: Copy config files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/home/{{ username }}/{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
  loop:
    - .config/alacritty/alacritty.toml
    - .config/i3/config
    - .bash_profile

- name: Copy executable config files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/home/{{ username }}/{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'
  loop:
    - .config/i3/i3-restart.sh
    - .xinitrc
