---
# code: language=ansible

- name: Install GUI
  ansible.builtin.import_tasks: 01-install.yml
  tags: gui-install

- name: Configure GUI
  ansible.builtin.import_tasks: 02-config.yml
  tags: gui-config
