---
# code: language=ansible

- name: Install required packages
  community.general.pacman:
    name:
      - kodi
      - firefox
      - i3-wm
      - alacritty
      - xorg-xinit
      - xorg-server
      - xorg-xrandr
    state: present
    update_cache: true

- name: Create .config subfolder
  ansible.builtin.file:
    path: "/home/{{ username }}/.config/i3"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'

- name: Add i3wm config
  ansible.builtin.copy:
    src: i3wm-config
    dest: "/home/{{ username }}/.config/i3/config"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'

- name: Add i3wm restart script
  ansible.builtin.copy:
    src: i3-restart.sh
    dest: "/home/{{ username }}/.config/i3/i3-restart.sh"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'

- name: Configure .xinitrc for automatic i3 startup
  ansible.builtin.copy:
    dest: "/home/{{ username }}/.xinitrc"
    src: xinitrc
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'

- name: Configure automatic Xorg start on login
  ansible.builtin.copy:
    dest: "/home/{{ username }}/.bash_profile"
    src: bash_profile
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'
