---
# code: language=ansible

# supported variants: i3 and labwc
desktop: labwc

# paths for config files & folders
subfolders:
  i3: ["i3", "alacritty"]
  labwc: ["labwc", "alacritty"]
configs:
  i3:
    - .config/alacritty/alacritty.toml
    - .config/i3/config
  labwc:
    - .config/alacritty/alacritty.toml
    - .config/labwc/rc.xml
    - .config/labwc/menu.xml
configs_exec:
  i3:
    - .config/i3/i3-restart.sh
    - .xinitrc
  labwc:
    - .config/labwc/autostart
