---
# code: language=ansible

- name: Add folders for Vaultwarden files
  ansible.builtin.file:
    path: "/home/{{ username }}/docker/{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'
  loop:
    - vw
    - vw/data

- name: Create Docker Compose file
  ansible.builtin.template:
    src: vaultwarden-compose.yml.j2
    dest: "{{ docker_path }}/vw/docker-compose.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0644'

- name: Launch Vaultwarden service
  community.docker.docker_compose_v2:
    project_src: "{{ docker_path }}/vw"
    recreate: auto
    remove_orphans: false
