---
# code: language=ansible

- name: Copy ansible-pull timer to systemd folder
  ansible.builtin.copy:
    src: ansible-pull.timer
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: "0644"

- name: Copy ansible-pull service to systemd folder
  ansible.builtin.template:
    src: ansible-pull.service.j2
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: "0644"

- name: Enable ansible-pull timer
  ansible.builtin.systemd:
    unit: ansible-pull.timer
    daemon_reload: true
    state: started
    enabled: true
