---
# code: language=ansible

- name: Install required packages
  community.general.pacman:
    name:
      - pipewire
      - pipewire-pulse
      - pipewire-alsa
      - wireplumber
      - alsa-utils
      - rtkit
    state: present
    update_cache: true

- name: Enable rtkit daemon
  ansible.builtin.systemd:
    name: rtkit-daemon
    state: started
    enabled: true

- name: Enable PipeWire services for user
  become: true
  become_user: "{{ username }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ lookup('ansible.builtin.pipe', 'id -u ' + username) }}"
  ansible.builtin.systemd:
    scope: user
    daemon_reload: true
    enabled: true
    name: "{{ item }}"
    state: started
  loop:
    - pipewire
    - pipewire-pulse
    - wireplumber

- name: Change volume to 100%
  become: true
  become_user: "{{ username }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ lookup('ansible.builtin.pipe', 'id -u ' + username) }}"
  ansible.builtin.command: "wpctl set-volume @DEFAULT_SINK@ 1.0"
  changed_when: false
