---
# code: language=ansible

- name: Install required packages
  community.general.pacman:
    name:
      - pipewire
      - pipewire-pulse
      - pipewire-alsa
      - wireplumber
      - alsa-utils
    state: present
    update_cache: true

- name: Enable PipeWire services for user
  become: true
  become_user: "{{ username }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ lookup('ansible.builtin.pipe', 'id -u ' + username) }}"
  ansible.builtin.systemd:
    scope: user
    daemon_reload: true
    enabled: true
    name: "{{ item }}"
    state: started
  loop:
    - pipewire
    - pipewire-pulse
    - wireplumber

- name: Get ID of audio card
  become: true
  become_user: "{{ username }}"
  ansible.builtin.shell: |
    set -eo pipefail
    pactl list cards | grep 'Card #' | awk '{print $2}' | tr -d '#'
  register: card_id
  changed_when: false

- name: Set audio card profile
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command: "pactl set-card-profile {{ card_id }} output:hdmi-stereo"
  changed_when: false

- name: Change volume to 100%
  become: true
  become_user: "{{ username }}"
  ansible.builtin.command: "wpctl set-volume @DEFAULT_SINK@ 1.0"
  changed_when: false
