---
# code: language=ansible

- name: Enable ansible-pull
  ansible.builtin.import_tasks: 01-ansible_pull.yml
  tags: ansible-pull

- name: Configure normal user
  ansible.builtin.import_tasks: 02-configure_user.yml
  tags: user

- name: Configure udev-media-automount
  ansible.builtin.import_tasks: 03-udev-media-automount.yml
  when: "'udev-media-automount' in base_components"
  tags: udev-media-automount

# Always clean up the legacy user automounter during migration.
- name: Remove legacy udiskie
  ansible.builtin.import_tasks: 03-udiskie_remove.yml
  tags: [udev-media-automount, udiskie]

- name: Remove udev-media-automount
  ansible.builtin.import_tasks: 03-udev-media-automount_remove.yml
  when: "'udev-media-automount' not in base_components"
  tags: udev-media-automount

- name: Configure pipewire
  ansible.builtin.import_tasks: 04-pipewire.yml
  when: "'pipewire' in base_components"
  tags: pipewire

- name: Remove pipewire
  ansible.builtin.import_tasks: 04-pipewire_remove.yml
  when: "'pipewire' not in base_components"
  tags: pipewire

- name: Configure dnsmasq
  ansible.builtin.import_tasks: 05-dnsmasq.yml
  when: "'dnsmasq' in base_components"
  tags: dnsmasq

- name: Remove dnsmasq
  ansible.builtin.import_tasks: 05-dnsmasq_remove.yml
  when: "'dnsmasq' not in base_components"
  tags: dnsmasq

- name: Configure reflector
  ansible.builtin.import_tasks: 06-reflector.yml
  when: "'reflector' in base_components"
  tags: reflector

- name: Remove reflector
  ansible.builtin.import_tasks: 06-reflector_remove.yml
  when: "'reflector' not in base_components"
  tags: reflector
