---
# code: language=ansible

- name: Enable ansible-pull
  ansible.builtin.import_tasks: 01-ansible_pull.yml
  tags: ansible-pull

- name: Configure normal user
  ansible.builtin.import_tasks: 02-configure_user.yml
  tags: configure-user

- name: Configure udiskie
  ansible.builtin.import_tasks: 03-udiskie.yml
  tags: udiskie

- name: Configure pipewire
  ansible.builtin.import_tasks: 04-pipewire.yml
  tags: pipewire
