name: Renovate Bot CI

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Run Renovate Bot
        uses: renovatebot/github-action@v43.0.3
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
